#!/bin/bash
BL_FILE=/tmp/hosts-zero
BL_URL=https://someonewhocares.org/hosts/zero/hosts


WS="\b(?=\w)"
WE="\b(?<=\w)"

IPV4_OCT="${WS}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])${WE}"
IPV6_SEG="${WS}[0-9a-f]{1,4}${WE}"

REGEX_IPV4="((?i)(${IPV4_OCT}\.){3}${IPV4_OCT})"

REGEX_IPV6="((?i)((${IPV6_SEG}:){7}${IPV6_SEG}|\
(${IPV6_SEG}:){1,7}:|\
(${IPV6_SEG}:){1,6}:${IPV6_SEG}|\
(${IPV6_SEG}:){1,5}(:${IPV6_SEG}){1,2}|\
(${IPV6_SEG}:){1,4}(:${IPV6_SEG}){1,3}|\
(${IPV6_SEG}:){1,3}(:${IPV6_SEG}){1,4}|\
(${IPV6_SEG}:){1,2}(:${IPV6_SEG}){1,5}|\
${IPV6_SEG}:(:${IPV6_SEG}){1,6})|\
::${IPV6_SEG}(:${IPV6_SEG}){0,6}|\
${IPV6_SEG}(:${IPV6_SEG}){0,6}::|\
[f][e]08:(:${IPV6_SEG}){2}%[0-9a-z]+)"


REGEX_IPV64="((?i)(::(0{1,4}:){1,5}|(0{1,4}:){6}|((0{1,4}:){1,5}|::((0{1,4}:){1,4})?)[f]{4}:)${REGEX_IPV4})"

REGEX_IP="(?(?=\A(:|${IPV6_SEG})*:${REGEX_IPV4}\Z)\A${REGEX_IPV64}\Z|(?(?=\A${REGEX_IPV4}\Z)\A${REGEX_IPV4}\Z|\A${REGEX_IPV6}\Z))"

function unit_test() {
    ip_set=("0.0.0.0" "127.0.0.1" "255.255.255.255" "256.254.253.252" "255.255.255.256" "255.255.2555.252" "255.255.25.252" "233.221.3" "fe80::e484:21:bfb3:9fc1" "fz80:fd490::1" "::1" "abCd:3040::1" "ABCD::0" "repeat::again::0" "2001:0DB8:0::0:1428:192.0.1.1" "2001:0Db8::0:192.0.1.1" "::ffff:127.0.0.1" "::127.0.0.1")
    ip_wc=(1 1 1 0 0 0 1 0 1 0 1 1 1 0 0 0 1 1)
    i=0
    for ip in ${ip_set[@]}; do
        output=$(echo ${ip} | grep -P "${REGEX_IP}" | wc -l)
        if [ ${output} -ne ${ip_wc[${i}]} ]; then
            echo "Error: ${ip} should output ${ip_wc[${i}]} but it resulted in ${output}."
            echo "Matched string: $(echo ${ip} | grep -Po "${REGEX_IP}")"
            exit 1
        fi
        i=$(expr $i + 1)
    done
}

if [ x${1} = x"test" ]; then
    unit_test
    exit 0
fi

wget -O ${BL_FILE} ${BL_URL}
if [[ 0 -eq $? && -f /etc/hosts-original ]]; then
    INVALID=$(cat ${BL_FILE} | gawk 'BEGIN{FS="[[:space:]]"};/^[^#[:cntrl:][:space:]]*/{print $1};END{}' - | grep -P "${REGEX_IP}" | grep -Pv '(?i)(0\.0\.0\.0|127\.0\.[01]\.1|255\.255\.255\.255|::[01]*|[f][ef]0[02]::[0-3])' | wc -l)
    if [ ${INVALID} -ne 0 ]; then
        /usr/bin/logger -p 'cron.err' 'Update of hosts file failed. Unknown IPs found.'
        exit 1
    fi
    /usr/bin/logger -p 'cron.info' "Updating hosts file with ${BL_URL}"
    cat /etc/hosts-original /tmp/hosts-zero > /etc/hosts
    rm /tmp/hosts-zero
else
    /usr/bin/logger -p 'cron.err' 'Update of hosts file failed. Please check that Internet is available and that /etc/hosts-original exists.'
fi


# Other black lists:
# http://winhelp2002.mvps.org/hosts.txt
# https://adaway.org/hosts.txt
# https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext
# https://www.malwaredomainlist.com/hostslist/hosts.txt
